###
# create birth report
POST /residents/4/death HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber": 8,
  "birthDeathReportDate": "2012-04-17",
  "deathReportQualificationsCode": "비동거친족",
  "emailAddress": null,
  "phoneNumber": "010-1234-4568"
}

###
# modify birth report
PUT /residents/4/death/8
Host: localhost:8080
Content-Type: application/json

{
  "birthDeathReportDate": "2012-04-18",
  "deathReportQualificationsCode": "동거친족",
  "emailAddress": "namnam@nav.com",
  "phoneNumber": "010-1122-3344"
}

###
# delete birth report
DELETE /residents/4/death/8
Host: localhost:8080
Content-Type: application/json