###
# create household
POST /household HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "householdSerialNumber": 2,
  "householdResidentSerialNumber": 9,
  "householdCompositionDate": "2020-12-12",
  "householdCompositionReasonCode": "세대분리",
  "currentHouseMovementAddress": "김해시 내외동 어쩌구저쩌구"
}

###
# delete household
DELETE /household/2
Host: localhost:8080
Content-Type: application/json